SolaceDev/solace-ai-connector

.github/workflows/release.yaml, pyproject.toml
Adding the publish workflow. The workflow will be manually run and then:
* Build
* Upversion depending on the input (patch, minor, major)
* Create Github Release
* Publish to pypi
No keys are needed because of [PyPi's trusted publishing](https://docs.pypi.org/trusted-publishers/). All we have to do is add a deploy key on the SolaceLabs repository as well as configure the github environment
=> DATAGO-79372: Add Publish workflow

.github/workflows/release.yaml
[DATAGO-83398](https://sol-jira.atlassian.net/browse/DATAGO-83398)
PYPI  currently does not allow trusted publishers for reusable workflows 
So we need to use PYPI API token to release using the action
See also 
[PR to solace-public-workflows](https://github.com/SolaceDev/solace-public-workflows/pull/3)
[DATAGO-83398]: https://sol-jira.atlassian.net/browse/DATAGO-83398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DATAGO-83398: Use PYPI token authentication

src/solace_ai_connector/components/inputs_outputs/broker_base.py, src/solace_ai_connector/components/inputs_outputs/broker_input.py
This pull request adds support for a temporary queue with a UUID queue name. Previously, the code only supported a fixed queue name for the broker. Now, if a queue name is not provided, a temporary queue will be created with a randomly generated UUID as the queue name. This allows for more flexibility and avoids conflicts with existing queue names.
=> Add support for temporary queue with UUID queue name

docs/configuration.md, examples/llm/mixture_of_agents.yaml, src/solace_ai_connector/common/invoke_functions.py, src/solace_ai_connector/components/inputs_outputs/broker_base.py, tests/test_invoke.py
Added a complex example on how to use solace-ai-connector
Implmenented the Mixture of Agent paper using solace-ai-connector
A UUID generator invoke function has also been added
=> Added MoA Example + UUID Invoke Function

docs/components/langchain_vector_store_embedding_index.md, docs/components/langchain_vector_store_embedding_search.md, examples/llm/openai_chat.yaml, examples/llm/openai_chroma_rag.yaml, examples/milvus_store.yaml, src/solace_ai_connector/components/general/langchain/langchain_vector_store_embedding_base.py, src/solace_ai_connector/components/general/langchain/langchain_vector_store_embedding_index.py, src/solace_ai_connector/components/general/langchain/langchain_vector_store_embedding_search.py
This pull request adds a RAG (Retrieval Augmented Generation) example for the AI connector. The example includes two flows: one for data ingestion and one for RAG inference. The data ingestion flow allows data to be sent to a Solace topic and then embedded and stored in ChromaDB. The RAG inference flow retrieves the top-k documents from ChromaDB, generates a response using the retrieved data, and sends the response back to the Solace broker.
=> Add RAG example for AI connector + delete action for vector index

config.yaml, examples/ack_test.yaml, examples/anthropic_bedrock.yaml, examples/error_handler.yaml, examples/request_reply.yaml
=> Fix for anthropic example

pyproject.toml, requirements.txt
This PR updates the version dependencies for `langchain` and `langchain-core` to ensure compatibility with the latest features and improvements. The versions have been incremented to `0.3.0` for both packages.
=> Update version dependencies for langchain and langchain-core

docs/guides/RAG.md, docs/guides/index.md, docs/index.md
This pull request introduces a new guide for RAG (Retrieval-Augmented Generation) in the documentation. The guide provides comprehensive insights on utilizing the Solace AI Connector effectively. Additionally, a link to the guide has been added to the main documentation index for easier access.
=> Add guide for RAG

docs/advanced_component_features.md, docs/configuration.md, docs/custom_components.md, docs/index.md, examples/llm/custom_components/llm_streaming_custom_component.py, examples/llm/openai_component_request_response.yaml, src/solace_ai_connector/common/event.py, src/solace_ai_connector/components/component_base.py, src/solace_ai_connector/components/general/delay.py, src/solace_ai_connector/components/general/for_testing/handler_callback.py, src/solace_ai_connector/components/general/openai/openai_chat_model_base.py, src/solace_ai_connector/components/inputs_outputs/broker_base.py, src/solace_ai_connector/components/inputs_outputs/broker_input.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py, src/solace_ai_connector/components/inputs_outputs/stdin_input.py, src/solace_ai_connector/components/inputs_outputs/stdout_output.py, src/solace_ai_connector/flow/flow.py, src/solace_ai_connector/flow/request_response_controller.py, src/solace_ai_connector/flow/request_response_flow_controller.py, src/solace_ai_connector/solace_ai_connector.py, src/solace_ai_connector/test_utils/utils_for_test_files.py, tests/test_request_response_controller.py
This PR adds the 'do_broker_request_response' function to ComponentBase to make it very easy for custom components to use broker-attached services.
I have added:
1. A new request_response_flow_controller class to manage an auto-created flow with a single 'broker_request_response' component in it
2. Optional configuration and implementation in ComponentBase to allow a custom component to use this
3. Some tests to ensure it works
4. Documentation on how to use it
5. An example of a custom component making use of it
=> AI-124: Add a feature to provide simple blocking broker request/response ability for components

.github/workflows/ci.yml, .github/workflows/release.yaml, pyproject.toml
Minimum python version changed in langchain core package to be 3.9 so we have to bump the version as well to fix CI
=> DATAGO-85484 Bump min python version

src/solace_ai_connector/main.py
This adds the ability to do:
```
!include my_stuff_at_root.yaml
my_obj:
!include my_sub_object.yaml
```
This will copy the specified file (relative to current file) into the current file and do this recursively. If the !include directive is indented, then that amount of space will be added to each line of the inserted file.
=> AI-173: Support !include in yaml config files

src/solace_ai_connector/common/messaging/dev_broker_messaging.py, src/solace_ai_connector/common/messaging/messaging.py, src/solace_ai_connector/common/messaging/messaging_builder.py, src/solace_ai_connector/common/messaging/solace_messaging.py, src/solace_ai_connector/components/inputs_outputs/broker_base.py, src/solace_ai_connector/components/inputs_outputs/broker_input.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py
This change adds a 'dev_broker' broker_type that behaves like a Solace Broker, but just runs within the context of a single solace-ai-connector. As long as all flows are running within the same instance, then they can all use broker_type='dev_broker' and they will communicate like normal.
This should be fully backwards compatible.
Note - this was built on top of the websocket component changes, so the diff is against that branch.
=> AI-170: Add new broker type: dev_broker

src/solace_ai_connector/components/component_base.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py
With this change, you can add a configuration to agents to control if and where the reply topic should be placed in the request
=> AI-354: Add configuration for broker-request-response for placing the reply topic in the message

src/solace_ai_connector/components/general/db/mongo/mongo_insert.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py
The purpose of this change is to improve error handling and robustness of the MongoDB insert operations and ensure that all broker messages are acknowledged properly in the request-response mechanism.
- Added message ack for request response: This ensures that messages are acknowledged upon receipt, which improves the stability and reliability of the messaging system.
- Enhanced error logging and validation for MongoDB insert configurations: This helps in diagnosing issues by providing clear error messages if incorrect data types or formats are provided.
Reviewers should focus on the implementation of the message acknowledgment in the messaging service and ensure it does not introduce any unintended side effects. Additionally, validate that the error handling improvements align with …
=> AI-429: Implement message acknowledgment for request-response pattern

examples/broker_input_output.yaml, src/solace_ai_connector/common/messaging/solace_messaging.py, src/solace_ai_connector/components/inputs_outputs/broker_base.py
Failed messages may stay in the queue forever. We need to set the maximum number of redelivering. If all retries fail, the message should be dropped.
Added _max_redelivery_count_ to the broker configuration and overwrote the broker default setting.
Nothing
=> DATAGO-94939: Configure maximum redelivery message for the broker

src/solace_ai_connector/components/general/llm/litellm/litellm_base.py
Currently the following error is thrown if model name, api key or base url is undefined. This is quite unintuitive for the user. Adding a validation step for the model config allows us to throw a more descriptive error.
`Error creating flows: Error initializing load balancer: unsupported operand type(s) for +=: 'NoneType' and 'str'
Error during Solace AI Event Connector startup: Error initializing load balancer: unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback: Traceback (most recent call last):
File "/Users/edfunnekotter/demo-test/solace-agent-mesh-demos/.venv/lib/python3.10/site-packages/solace_ai_connector/components/general/llm/litellm/litellm_base.py", line 158, in init_load_balancer
self.router = litellm.Router(
File …
=> AI-484: Throw better error if model config is invalid 

src/solace_ai_connector/components/general/llm/litellm/litellm_chat_model_base.py
Handling litellm errors (e.g. ContextWindowExceededError, InternalServerError, RateLimitError).
Prior to this change, litellm errors were not handled properly and would result in reinvoking the orchestrator until Timeout.
Catching any APIConnectionErrors and returning the error message to the orchestrator.
This is a multi-repository change, must be implemented after the SAM PR (AI-308).
=> AI-308: Handle litellm errors

pyproject.toml, requirements.txt, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py, src/solace_ai_connector/flow/request_response_flow_controller.py, src/solace_ai_connector/main.py
~~Extend request time if the orchestrator is still streaming responses, but lower timeout limit if the orchestrator is not streaming back.~~
Continue streaming messages as long as the orchestrator receives messages.
Benefits: Permit longer requests while also catching orchestrator timeouts faster.
Windows users can now exit using `CTRL + C` from Powershell
~~New config `activity_timeout_s` that will raise a TimeoutError if the last activity time of a streamed response in more than its value.~~
Extend `remaining_timeout` value at each streamed messages received.
~~Will have to up the value `request_expiry_ms` in `orchestrator.yaml` file (possibly 300000). Could also add the new config `activity_timeout_s`.~~
I tried to handle TimeoutErrors differently, even though it could almost work …
=> AI-559: Orchestrator timeout errors & Gracefully exit on windows

src/solace_ai_connector/flow/request_response_flow_controller.py
What is the purpose of this change?
To prevent potential issues with timeouts by ensuring the remaining timeout value is never set to zero or negative.
How is this accomplished?
The code now uses max(0, self.request_expiry_s - elapsed_time) when calculating the remaining timeout value, ensuring it always has a positive value when passed to queue operations.
In extremely rare timing conditions, the remaining timeout calculated to a negative value when reading from the llm response queue. This caused the queue read to fail, but left the llm response on the queue for the next request to read. This issue is not recoverable.
Anything reviews should focus on/be aware of?
Reviewers should verify that this fix properly handles the edge case where elapsed time equals or exceeds the request expiry …
=> AI-644: Fix queue timeout issue when reading from request response queue.

src/solace_ai_connector/components/general/llm/litellm/litellm_base.py
🧩 Complexity Level: 🟢 Low
⏱️ Estimated Review Time: 5 minutes
Handling `ContextWindowExceeded` errors properly. Instead of a timeout, the orchestrator receives a 'Input is too long' response.
Adding another except statement, filtering for `ContextWindowExceeded` and simulating a Model response.
=> AI-795: Fix to timeout when context exceeded
