src/solace_ai_connector/components/general/user_processor.py, tests/test_filter.py
Fixed a small problem of what data is returned from the user_processor component
=> User_processor_fix

src/solace_ai_connector/components/inputs_outputs/timer_input.py
Fixed an issue where the timer would get progressively shorter over time.
=> Fix_timer_issue

docs/components/file_output.md, docs/components/index.md, docs/components/timer_input.md, src/solace_ai_connector/common/message.py, src/solace_ai_connector/components/inputs_outputs/file_output.py, src/solace_ai_connector/components/inputs_outputs/timer_input.py
Added a new component: file_output to write messages to files
=> File_output-component

.github/workflows/ci.yml, .github/workflows/release.yaml, pyproject.toml
Use shareable actions for release and CI workflows
=> DATAGO-80480: Change workflows to use shareable public actions

docs/components/langchain_chat_model_with_history.md, docs/components/timer_input.md, src/solace_ai_connector/components/component_base.py, src/solace_ai_connector/components/general/langchain/langchain_chat_model_with_history.py, src/solace_ai_connector/components/inputs_outputs/timer_input.py
* Improved streaming to allow multiple streams to exist concurrently
* Provide a more explicit way to discard messages in components
=> Better_streaming

src/solace_ai_connector/common/log.py
Just a small change in the log config
=> Set the log level to the min between STDOUT and file

.github/workflows/release.yaml
Fix for shareable release action
=> fix: Add contents:write permission to release workflow

src/solace_ai_connector/common/invoke_functions.py, tests/test_invoke.py
Just added another simple invoke function
=> Add_if_else_invoke

Dockerfile, Makefile, docs/configuration.md, docs/getting_started.md, docs/overview.md, docs/usage.md, src/solace_ai_connector/common/log.py
- Added clarifications
- Added instruction for creating a local solace broker
- Update Makefile and Dockerfile with minor details
- Fixed bug with writing stream file
=> Updated documentations + File log bug fix

examples/llm/mixture_of_agents.yaml, src/solace_ai_connector/components/inputs_outputs/broker_base.py, src/solace_ai_connector/flow/flow.py, src/solace_ai_connector/main.py, src/solace_ai_connector/solace_ai_connector.py
This pull request fixes the solace disconnection issues that occur when shutting down the application. The changes ensure that the solace connection is properly disconnected when stopping the component.
also fixed the intrupt issue
=> Fix solace disconnection issues on shutting down

docs/getting_started.md
This PR updates the URL and file name in the getting started section to reflect the correct configuration file for the OpenAI connector. The changes ensure that users can successfully download and run the example without confusion.
=> Fix URL and file name in getting started guide

docs/guides/RAG.md
[Added link to other docs from RAG guide](https://github.com/SolaceDev/solace-ai-connector/commit/bfcb975fe01f8515385f4efbe74d4ba8ee222f74)
=> Added link to other docs from RAG guide

src/solace_ai_connector/test_utils/utils_for_test_files.py, tests/test_transforms.py
Small changes to increase the ability to test components that discard the message and return nothing
=> chore: added a timeout setting for running component tests so that you can test situations where you don't expect any output

src/solace_ai_connector/main.py
Add support for:
config_param: ${MY_ENV_VAR, "default_value"}
in .yaml config files
=> AI-129: Add support for default values when specifying environment variables in config files

docs/components/broker_request_response.md, docs/components/index.md, docs/components/openai_chat_model.md, docs/components/openai_chat_model_with_history.md, docs/components/stdin_input.md, docs/components/stdout_output.md, examples/llm/openai_component_request_response.yaml, examples/request_reply.yaml, src/solace_ai_connector/common/utils.py, src/solace_ai_connector/components/general/openai/openai_chat_model_base.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py
This pull request introduces several enhancements and fixes to multiple components, mainly focusing on the `BrokerRequestResponse` component, `OpenAI` components, and input/output elements. These updates aim to provide more robust functionality, improved configuration options, and better error handling.
1. **`broker_request_response.md` Documentation Updates**
- Added new configuration parameters:
- `response_topic_prefix`
- `response_topic_suffix`
- `reply_queue_prefix`
- Updated existing parameters for clarity and new functionality.
- Added new fields to the input schema for detailed configurations related to streaming responses.
- Enhanced description for streaming configuration parameters.
2. **`index.md` Documentation Updates**
- Updated the description of `stdin_input` and …
=> AI-95: Add retries to openai llm requests, cleaned up some request/response terminology and rebuild all the docs

src/solace_ai_connector/solace_ai_connector.py
Give better visibility of starting up with info logs
=> Change startup logs to info rather than debug to be the same as shutdown

src/solace_ai_connector/common/utils.py
**What is the purpose of this change?**
The filtering unit test is failing because we removed a component that the code was still referencing.
**How is this accomplished?**
The reference to the deleted component has been removed.
**Anything reviews should focus on/be aware of?**
=> Hotfix: Resolve Filtering Test Error

docs/components/index.md, docs/components/litellm_chat_model.md, docs/components/litellm_embeddings.md, src/solace_ai_connector/components/component_base.py, src/solace_ai_connector/components/inputs_outputs/websocket_base.py, src/solace_ai_connector/main.py, src/solace_ai_connector/solace_ai_connector.py
This pull request aims to improve the exit process for a more robust and user-friendly experience during application shutdown. It addresses the need for a force quit capability for single components and resolves the issue with the application not exiting properly on Ctrl-C command.
The changes introduce a more comprehensive cleanup logic to manage application and component shutdown. This includes capturing KeyboardInterrupts gracefully, ensuring that resources and threads are cleaned up properly, and implementing a force-quit mechanism for individual components. It also refactors the shutdown process to use atexit for cleaner application termination signals.
Reviewers should focus on ensuring that the changes maintain the stability of the existing application functionality while providing …
=> AI-131: Improve exit process to support force quit and fix ctrl-c issue

examples/custom_components/web_search.py, examples/parser.yaml, src/solace_ai_connector/components/general/parser.py, src/solace_ai_connector/solace_ai_connector.py
The purpose of this change is to enhance the parser component's functionality to support more data conversion formats, increasing its versatility in handling different input and output data types.
This is accomplished by expanding the parser component's configuration to include both input and output formats, allowing for conversions between JSON, YAML, and dictionary structures. Additionally, modifications in the component's logic ensure proper parsing and formatting of data according to the specified formats. The changes also involve updates to the example configurations and the overall structure of the component to align with these new capabilities.
Reviewers should focus on ensuring that the added flexibility in data format conversion does not introduce any incorrect parsing or …
=> AI-289: Enhance parser component with additional conversion support

src/solace_ai_connector/components/component_base.py, src/solace_ai_connector/components/inputs_outputs/broker_input.py, src/solace_ai_connector/components/inputs_outputs/broker_output.py, src/solace_ai_connector/flow/flow.py, tests/test_acks.py, tests/test_error_flows.py
Allow flows to turn off sending all errors to the error_queue and include the traceback in the error message
=> AI-287: A few changes to improve error reporting

docs/components/index.md, docs/components/parser.md, docs/components/web_scraper.md, docs/components/websearch_bing.md, docs/components/websearch_duckduckgo.md, docs/components/websearch_google.md, examples/websearch/bing_web_search.yaml, examples/websearch/duckduckgo_web_search.yaml, examples/websearch/google_web_search.yaml, examples/websearch/web_scraping.yaml, examples/websearch/websearch_router.yaml, src/solace_ai_connector/components/general/parser.py, src/solace_ai_connector/components/general/websearch/web_scraper.py, src/solace_ai_connector/components/general/websearch/websearch_base.py, src/solace_ai_connector/components/general/websearch/websearch_bing.py, src/solace_ai_connector/components/general/websearch/websearch_duckduckgo.py, src/solace_ai_connector/components/general/websearch/websearch_google.py, src/solace_ai_connector/components/inputs_outputs/broker_request_response.py
API refactor for web components + clean up
removed the stdin api for web components
updated duckduckgo api to return the same interface as others
n/a
=> AI-289: API refactor for web components + clean up

src/solace_ai_connector/common/log.py, src/solace_ai_connector/solace_ai_connector.py
The log format currently uses a pipe-separated structure, while the micro integration to the cloud requires a JSON format.
The log format option has been added to the configuration. By default, it is set to use a pipe-separated format.
=> Alireza/ai 167/ai micro integration new

.github/workflows/ci.yml, .github/workflows/release.yaml, pyproject.toml
- Bump minimum python version to 3.10
- Use updated build workflow setup
=> DATAGO-87497: Update for CI improvements

examples/llm/anthropic_chat.yaml, src/solace_ai_connector/components/general/llm/langchain/langchain_chat_model.py, src/solace_ai_connector/components/general/llm/langchain/langchain_chat_model_base.py, src/solace_ai_connector/components/general/llm/langchain/langchain_chat_model_with_history.py, src/solace_ai_connector/components/general/llm/litellm/litellm_base.py, src/solace_ai_connector/components/general/llm/litellm/litellm_chat_model_base.py, src/solace_ai_connector/components/general/llm/litellm/litellm_chat_model_with_history.py, src/solace_ai_connector/components/general/llm/openai/openai_chat_model_base.py, src/solace_ai_connector/components/general/llm/openai/openai_chat_model_with_history.py
The purpose of this change is to enhance the existing functionality by allowing streaming of responses at the event level within Large Language Model (LLM) chats. This modification aims to provide greater flexibility and control over how streaming operates in the context of different events, facilitating more dynamic interactions and improving the user experience with asynchronous data flows.
- **Using this, the same LLM service component can stream or not depending on the event**
This change is accomplished by introducing a new configuration option that allows streaming to be enabled or disabled on a per-event basis. The implementation includes modifications to the configuration files and underlying code to support this new option. Key components have been updated to handle the streaming …
=> FEATURE: Enable stream overwrite for LLM Chat at the event level

docs/components/broker_request_response.md, docs/components/error_input.md, docs/components/index.md, docs/components/langchain_chat_model.md, docs/components/langchain_chat_model_with_history.md, docs/components/litellm_chat_model.md, docs/components/litellm_chat_model_with_history.md, docs/components/litellm_embeddings.md, docs/components/mongo_base.md, docs/components/mongo_insert.md, docs/components/mongo_search.md, docs/components/openai_chat_model.md, docs/components/openai_chat_model_with_history.md, pyproject.toml, src/solace_ai_connector/common/utils.py, src/solace_ai_connector/components/__init__.py, src/solace_ai_connector/components/general/db/mongo/mongo_base.py, src/solace_ai_connector/components/general/db/mongo/mongo_handler.py, src/solace_ai_connector/components/general/db/mongo/mongo_insert.py, src/solace_ai_connector/components/general/db/mongo/mongo_search.py
The primary purpose of this change is to enhance the system by adding a new component for handling MongoDB database operations. This enhancement is aimed at facilitating the insertion of JSON data into a MongoDB database seamlessly.
- Introduced a new component: **MongoDBInsertComponent** that handles database insert operations.
- Added necessary configurations and schemas to support the new component in different parts of the system.
- Implemented a **mongo_handler** for managing database connections and operations efficiently.
Reviewers should ensure the MongoDB configurations are appropriately set and validate the new functionality through comprehensive testing, especially for the MongoDB operations to check for potential errors or misconfigurations.
=> JDE: Add MongoDB insert component.

.github/workflows/ci.yml, wss-unified-agent.config
https://sol-jira.atlassian.net/browse/DATAGO-91907
- Adding whitesource_config_file to ci workflow
- Add new input for the `whitesource_config_file path` on ci
=> DATAGO-91907: Investigate Solace AI connector (other solace ai libs) whitesoure scan results.

src/solace_ai_connector/common/messaging/messaging_builder.py, src/solace_ai_connector/components/inputs_outputs/broker_base.py
If the broker_type is undefined, set it to 'solace'
=> AI-516: Default broker_type to 'solace'

.github/workflows/ci.yml, pyproject.toml
=> DATAGO-98405 -  Relax min python version requirement to 3.10.16 

.github/pull_request_template.md
We need to know the complexity of changes and estimation time of code review.
Added the complexity and estimation review time to pull requests.
=> DATAGO-99524

pyproject.toml, requirements.txt, src/solace_ai_connector/components/inputs_outputs/websocket_base.py, src/solace_ai_connector/components/inputs_outputs/websocket_output.py
Converting server to production ready
From flask dev server to Gevent production ready server
=> AI-693: Convert all instances of flask development server to production ready WSGI server

src/solace_ai_connector/components/general/db/mongo/mongo_insert.py
This change enhances the datetime parsing capabilities of the MongoDB insert component to handle problematic datetime string formats more gracefully. It adds robust error handling and cleanup for malformed datetime strings that contain redundant or conflicting timezone indicators.
- feat: enhance datetime parsing with cleanup for MongoDB inserts
- Added try-except blocks to handle parsing errors
- Implemented cleanup logic for common problematic patterns like "Z UTC" and duplicate UTC indicators
- Provided detailed error messages with supported format examples when parsing fails
- Maintains backward compatibility with existing valid datetime formats
Reviewers should verify the datetime cleanup logic handles real-world problematic cases without affecting valid formats. Consider testing …
=> DATAGO-102914: Enhance datetime parsing with cleanup for MongoDB inserts

src/solace_ai_connector/services/cache_service.py
Purpose: Improve cache expiry handling by adding expiry events and fixing inconsistent expiry logic across storage backends.
Main changes:
- Added _send_expiry_event method to notify components when cached items expire
- Fixed storage consistency by standardizing how expired items are removed
- Refactored expiry time calculation to use absolute timestamps consistently
_Generated by LinearB AI and added by gitStream._
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your feedback!](mailto:product@linearb.io)** 🚀</sub>
=> DATAGO-106571: Fixed cache service expiration bugs
